In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
df=pd.read_csv('online_gaming_behavior_dataset.csv')
df

PlayerID  Age  Gender Location   GameGenre  PlayTimeHours  \
0          9000   43    Male    Other    Strategy      16.271119   
1          9001   29  Female      USA    Strategy       5.525961   
2          9002   22  Female      USA      Sports       8.223755   
3          9003   35    Male      USA      Action       5.265351   
4          9004   33    Male   Europe      Action      15.531945   
...         ...  ...     ...      ...         ...            ...   
40029     49029   32    Male      USA    Strategy      20.619662   
40030     49030   44  Female    Other  Simulation      13.539280   
40031     49031   15  Female      USA         RPG       0.240057   
40032     49032   34    Male      USA      Sports      14.017818   
40033     49033   19    Male      USA      Sports      10.083804   

       InGamePurchases GameDifficulty  SessionsPerWeek  \
0                    0         Medium                6   
1                    0         Medium                5   
2                    0           Easy               16   
3                    1           Easy                9   
4                    0         Medium                2   
...                ...            ...              ...   
40029                0           Easy                4   
40030                0           Hard               19   
40031                1           Easy               10   
40032                1         Medium                3   
40033                0           Easy               13   

       AvgSessionDurationMinutes  PlayerLevel  AchievementsUnlocked  \
0                            108           79                    25   
1                            144           11                    10   
2                            142           35                    41   
3                             85           57                    47   
4                            131           95                    37   
...                          ...          ...                   ...   
40029                         75           85                    14   
40030                        114           71                    27   
40031                        176           29                     1   
40032                        128           70                    10   
40033                         84           72                    39   

      EngagementLevel  
0              Medium  
1              Medium  
2                High  
3              Medium  
4              Medium  
...               ...  
40029          Medium  
40030            High  
40031            High  
40032          Medium  
40033          Medium  

[40034 rows x 13 columns]

In [16]:
df.columns

Index(['PlayerID', 'Age', 'Gender', 'Location', 'GameGenre', 'PlayTimeHours',
       'InGamePurchases', 'GameDifficulty', 'SessionsPerWeek',
       'AvgSessionDurationMinutes', 'PlayerLevel', 'AchievementsUnlocked',
       'EngagementLevel'],
      dtype='object')

In [17]:
df.isnull().sum()

PlayerID                     0
Age                          0
Gender                       0
Location                     0
GameGenre                    0
PlayTimeHours                0
InGamePurchases              0
GameDifficulty               0
SessionsPerWeek              0
AvgSessionDurationMinutes    0
PlayerLevel                  0
AchievementsUnlocked         0
EngagementLevel              0
dtype: int64

In [18]:
label_encoder=LabelEncoder()
df['EngagementLevel']=label_encoder.fit_transform(df['EngagementLevel'])
df['EngagementLevel'].unique()
df['GameGenre']=label_encoder.fit_transform(df['GameGenre'])
df.corr()

C:\Users\arunp\AppData\Local\Temp\ipykernel_8644\2532075580.py:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


PlayerID       Age  GameGenre  PlayTimeHours  \
PlayerID                   1.000000 -0.003044  -0.002314       0.000923   
Age                       -0.003044  1.000000   0.004343       0.002462   
GameGenre                 -0.002314  0.004343   1.000000      -0.004226   
PlayTimeHours              0.000923  0.002462  -0.004226       1.000000   
InGamePurchases            0.002321 -0.000186   0.012843      -0.006067   
SessionsPerWeek           -0.005944  0.008777   0.005616      -0.003655   
AvgSessionDurationMinutes -0.001801 -0.002269   0.008697      -0.001925   
PlayerLevel               -0.001769  0.001353   0.003220      -0.005152   
AchievementsUnlocked       0.003190 -0.001100  -0.001240       0.003913   
EngagementLevel           -0.002817  0.007433  -0.003407      -0.007644   

                           InGamePurchases  SessionsPerWeek  \
PlayerID                          0.002321        -0.005944   
Age                              -0.000186         0.008777   
GameGenre                         0.012843         0.005616   
PlayTimeHours                    -0.006067        -0.003655   
InGamePurchases                   1.000000         0.005132   
SessionsPerWeek                   0.005132         1.000000   
AvgSessionDurationMinutes        -0.003059        -0.000620   
PlayerLevel                       0.006524         0.003257   
AchievementsUnlocked              0.000098         0.003187   
EngagementLevel                  -0.005949        -0.249474   

                           AvgSessionDurationMinutes  PlayerLevel  \
PlayerID                                   -0.001801    -0.001769   
Age                                        -0.002269     0.001353   
GameGenre                                   0.008697     0.003220   
PlayTimeHours                              -0.001925    -0.005152   
InGamePurchases                            -0.003059     0.006524   
SessionsPerWeek                            -0.000620     0.003257   
AvgSessionDurationMinutes                   1.000000     0.001368   
PlayerLevel                                 0.001368     1.000000   
AchievementsUnlocked                       -0.002227     0.006343   
EngagementLevel                            -0.293893     0.013185   

                           AchievementsUnlocked  EngagementLevel  
PlayerID                               0.003190        -0.002817  
Age                                   -0.001100         0.007433  
GameGenre                             -0.001240        -0.003407  
PlayTimeHours                          0.003913        -0.007644  
InGamePurchases                        0.000098        -0.005949  
SessionsPerWeek                        0.003187        -0.249474  
AvgSessionDurationMinutes             -0.002227        -0.293893  
PlayerLevel                            0.006343         0.013185  
AchievementsUnlocked                   1.000000         0.015576  
EngagementLevel                        0.015576         1.000000

In [19]:
X = df[['SessionsPerWeek', 'AvgSessionDurationMinutes', 'PlayTimeHours', 'InGamePurchases', 'AchievementsUnlocked','PlayerLevel']]
y = df['EngagementLevel']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
clf = RandomForestClassifier(random_state=42)

In [21]:
print("Shape of X (features):", X.shape)
print("Shape of y (target):", y.shape)


Shape of X (features): (40034, 6)
Shape of y (target): (40034,)


In [22]:
print(df.isnull().sum())

PlayerID                     0
Age                          0
Gender                       0
Location                     0
GameGenre                    0
PlayTimeHours                0
InGamePurchases              0
GameDifficulty               0
SessionsPerWeek              0
AvgSessionDurationMinutes    0
PlayerLevel                  0
AchievementsUnlocked         0
EngagementLevel              0
dtype: int64


In [23]:
clf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [24]:
y_pred = clf.predict(X_test)

In [25]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Display classification report
print('Classification Report:')
print(classification_report(y_test, y_pred))

# Confusion matrix
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))

Accuracy: 91.57%
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.89      0.90      2035
           1       0.91      0.88      0.90      2093
           2       0.91      0.95      0.93      3879

    accuracy                           0.92      8007
   macro avg       0.92      0.91      0.91      8007
weighted avg       0.92      0.92      0.92      8007

Confusion Matrix:
[[1802   69  164]
 [  62 1851  180]
 [  91  109 3679]]


In [26]:
with open("model.pkl", "wb") as model_file:
    pickle.dump(clf, model_file)

with open("scaler.pkl", "wb") as scaler_file:
    pickle.dump(scaler, scaler_file)